-- Create "pastes" table
CREATE TABLE "pastes" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "slug" character varying NOT NULL,
  "title" character varying NULL,
  "content" text NOT NULL,
  "language" character varying NULL DEFAULT 'plaintext',
  "is_public" boolean NOT NULL DEFAULT true,
  "expires_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "paste_created_at" to table: "pastes"
CREATE INDEX "paste_created_at" ON "pastes" ("created_at");
-- Create index "paste_slug" to table: "pastes"
CREATE INDEX "paste_slug" ON "pastes" ("slug");
-- Create index "pastes_slug_key" to table: "pastes"
CREATE UNIQUE INDEX "pastes_slug_key" ON "pastes" ("slug");
