// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/piotmni/go-mini-templates/ent-atlas/ent/paste"
	"github.com/piotmni/go-mini-templates/ent-atlas/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypePaste = "Paste"
)

// PasteMutation represents an operation that mutates the Paste nodes in the graph.
type PasteMutation struct {
	config
	op            Op
	typ           string
	id            *int
	slug          *string
	title         *string
	content       *string
	language      *string
	is_public     *bool
	expires_at    *time.Time
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Paste, error)
	predicates    []predicate.Paste
}

var _ ent.Mutation = (*PasteMutation)(nil)

// pasteOption allows management of the mutation configuration using functional options.
type pasteOption func(*PasteMutation)

// newPasteMutation creates new mutation for the Paste entity.
func newPasteMutation(c config, op Op, opts ...pasteOption) *PasteMutation {
	m := &PasteMutation{
		config:        c,
		op:            op,
		typ:           TypePaste,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPasteID sets the ID field of the mutation.
func withPasteID(id int) pasteOption {
	return func(m *PasteMutation) {
		var (
			err   error
			once  sync.Once
			value *Paste
		)
		m.oldValue = func(ctx context.Context) (*Paste, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Paste.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPaste sets the old Paste of the mutation.
func withPaste(node *Paste) pasteOption {
	return func(m *PasteMutation) {
		m.oldValue = func(context.Context) (*Paste, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PasteMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PasteMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PasteMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PasteMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Paste.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSlug sets the "slug" field.
func (m *PasteMutation) SetSlug(s string) {
	m.slug = &s
}

// Slug returns the value of the "slug" field in the mutation.
func (m *PasteMutation) Slug() (r string, exists bool) {
	v := m.slug
	if v == nil {
		return
	}
	return *v, true
}

// OldSlug returns the old "slug" field's value of the Paste entity.
// If the Paste object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PasteMutation) OldSlug(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSlug is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSlug requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSlug: %w", err)
	}
	return oldValue.Slug, nil
}

// ResetSlug resets all changes to the "slug" field.
func (m *PasteMutation) ResetSlug() {
	m.slug = nil
}

// SetTitle sets the "title" field.
func (m *PasteMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *PasteMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Paste entity.
// If the Paste object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PasteMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ClearTitle clears the value of the "title" field.
func (m *PasteMutation) ClearTitle() {
	m.title = nil
	m.clearedFields[paste.FieldTitle] = struct{}{}
}

// TitleCleared returns if the "title" field was cleared in this mutation.
func (m *PasteMutation) TitleCleared() bool {
	_, ok := m.clearedFields[paste.FieldTitle]
	return ok
}

// ResetTitle resets all changes to the "title" field.
func (m *PasteMutation) ResetTitle() {
	m.title = nil
	delete(m.clearedFields, paste.FieldTitle)
}

// SetContent sets the "content" field.
func (m *PasteMutation) SetContent(s string) {
	m.content = &s
}

// Content returns the value of the "content" field in the mutation.
func (m *PasteMutation) Content() (r string, exists bool) {
	v := m.content
	if v == nil {
		return
	}
	return *v, true
}

// OldContent returns the old "content" field's value of the Paste entity.
// If the Paste object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PasteMutation) OldContent(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContent: %w", err)
	}
	return oldValue.Content, nil
}

// ResetContent resets all changes to the "content" field.
func (m *PasteMutation) ResetContent() {
	m.content = nil
}

// SetLanguage sets the "language" field.
func (m *PasteMutation) SetLanguage(s string) {
	m.language = &s
}

// Language returns the value of the "language" field in the mutation.
func (m *PasteMutation) Language() (r string, exists bool) {
	v := m.language
	if v == nil {
		return
	}
	return *v, true
}

// OldLanguage returns the old "language" field's value of the Paste entity.
// If the Paste object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PasteMutation) OldLanguage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLanguage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLanguage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLanguage: %w", err)
	}
	return oldValue.Language, nil
}

// ClearLanguage clears the value of the "language" field.
func (m *PasteMutation) ClearLanguage() {
	m.language = nil
	m.clearedFields[paste.FieldLanguage] = struct{}{}
}

// LanguageCleared returns if the "language" field was cleared in this mutation.
func (m *PasteMutation) LanguageCleared() bool {
	_, ok := m.clearedFields[paste.FieldLanguage]
	return ok
}

// ResetLanguage resets all changes to the "language" field.
func (m *PasteMutation) ResetLanguage() {
	m.language = nil
	delete(m.clearedFields, paste.FieldLanguage)
}

// SetIsPublic sets the "is_public" field.
func (m *PasteMutation) SetIsPublic(b bool) {
	m.is_public = &b
}

// IsPublic returns the value of the "is_public" field in the mutation.
func (m *PasteMutation) IsPublic() (r bool, exists bool) {
	v := m.is_public
	if v == nil {
		return
	}
	return *v, true
}

// OldIsPublic returns the old "is_public" field's value of the Paste entity.
// If the Paste object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PasteMutation) OldIsPublic(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsPublic is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsPublic requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsPublic: %w", err)
	}
	return oldValue.IsPublic, nil
}

// ResetIsPublic resets all changes to the "is_public" field.
func (m *PasteMutation) ResetIsPublic() {
	m.is_public = nil
}

// SetExpiresAt sets the "expires_at" field.
func (m *PasteMutation) SetExpiresAt(t time.Time) {
	m.expires_at = &t
}

// ExpiresAt returns the value of the "expires_at" field in the mutation.
func (m *PasteMutation) ExpiresAt() (r time.Time, exists bool) {
	v := m.expires_at
	if v == nil {
		return
	}
	return *v, true
}

// OldExpiresAt returns the old "expires_at" field's value of the Paste entity.
// If the Paste object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PasteMutation) OldExpiresAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpiresAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpiresAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpiresAt: %w", err)
	}
	return oldValue.ExpiresAt, nil
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (m *PasteMutation) ClearExpiresAt() {
	m.expires_at = nil
	m.clearedFields[paste.FieldExpiresAt] = struct{}{}
}

// ExpiresAtCleared returns if the "expires_at" field was cleared in this mutation.
func (m *PasteMutation) ExpiresAtCleared() bool {
	_, ok := m.clearedFields[paste.FieldExpiresAt]
	return ok
}

// ResetExpiresAt resets all changes to the "expires_at" field.
func (m *PasteMutation) ResetExpiresAt() {
	m.expires_at = nil
	delete(m.clearedFields, paste.FieldExpiresAt)
}

// SetCreatedAt sets the "created_at" field.
func (m *PasteMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *PasteMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Paste entity.
// If the Paste object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PasteMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *PasteMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *PasteMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *PasteMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Paste entity.
// If the Paste object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PasteMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *PasteMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the PasteMutation builder.
func (m *PasteMutation) Where(ps ...predicate.Paste) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PasteMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PasteMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Paste, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PasteMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PasteMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Paste).
func (m *PasteMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PasteMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.slug != nil {
		fields = append(fields, paste.FieldSlug)
	}
	if m.title != nil {
		fields = append(fields, paste.FieldTitle)
	}
	if m.content != nil {
		fields = append(fields, paste.FieldContent)
	}
	if m.language != nil {
		fields = append(fields, paste.FieldLanguage)
	}
	if m.is_public != nil {
		fields = append(fields, paste.FieldIsPublic)
	}
	if m.expires_at != nil {
		fields = append(fields, paste.FieldExpiresAt)
	}
	if m.created_at != nil {
		fields = append(fields, paste.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, paste.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PasteMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case paste.FieldSlug:
		return m.Slug()
	case paste.FieldTitle:
		return m.Title()
	case paste.FieldContent:
		return m.Content()
	case paste.FieldLanguage:
		return m.Language()
	case paste.FieldIsPublic:
		return m.IsPublic()
	case paste.FieldExpiresAt:
		return m.ExpiresAt()
	case paste.FieldCreatedAt:
		return m.CreatedAt()
	case paste.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PasteMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case paste.FieldSlug:
		return m.OldSlug(ctx)
	case paste.FieldTitle:
		return m.OldTitle(ctx)
	case paste.FieldContent:
		return m.OldContent(ctx)
	case paste.FieldLanguage:
		return m.OldLanguage(ctx)
	case paste.FieldIsPublic:
		return m.OldIsPublic(ctx)
	case paste.FieldExpiresAt:
		return m.OldExpiresAt(ctx)
	case paste.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case paste.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Paste field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PasteMutation) SetField(name string, value ent.Value) error {
	switch name {
	case paste.FieldSlug:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSlug(v)
		return nil
	case paste.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case paste.FieldContent:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContent(v)
		return nil
	case paste.FieldLanguage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLanguage(v)
		return nil
	case paste.FieldIsPublic:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsPublic(v)
		return nil
	case paste.FieldExpiresAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpiresAt(v)
		return nil
	case paste.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case paste.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Paste field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PasteMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PasteMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PasteMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Paste numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PasteMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(paste.FieldTitle) {
		fields = append(fields, paste.FieldTitle)
	}
	if m.FieldCleared(paste.FieldLanguage) {
		fields = append(fields, paste.FieldLanguage)
	}
	if m.FieldCleared(paste.FieldExpiresAt) {
		fields = append(fields, paste.FieldExpiresAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PasteMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PasteMutation) ClearField(name string) error {
	switch name {
	case paste.FieldTitle:
		m.ClearTitle()
		return nil
	case paste.FieldLanguage:
		m.ClearLanguage()
		return nil
	case paste.FieldExpiresAt:
		m.ClearExpiresAt()
		return nil
	}
	return fmt.Errorf("unknown Paste nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PasteMutation) ResetField(name string) error {
	switch name {
	case paste.FieldSlug:
		m.ResetSlug()
		return nil
	case paste.FieldTitle:
		m.ResetTitle()
		return nil
	case paste.FieldContent:
		m.ResetContent()
		return nil
	case paste.FieldLanguage:
		m.ResetLanguage()
		return nil
	case paste.FieldIsPublic:
		m.ResetIsPublic()
		return nil
	case paste.FieldExpiresAt:
		m.ResetExpiresAt()
		return nil
	case paste.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case paste.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Paste field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PasteMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PasteMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PasteMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PasteMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PasteMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PasteMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PasteMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Paste unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PasteMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Paste edge %s", name)
}
