// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/piotmni/go-mini-templates/ent-atlas/ent/paste"
	"github.com/piotmni/go-mini-templates/ent-atlas/ent/predicate"
)

// PasteUpdate is the builder for updating Paste entities.
type PasteUpdate struct {
	config
	hooks    []Hook
	mutation *PasteMutation
}

// Where appends a list predicates to the PasteUpdate builder.
func (_u *PasteUpdate) Where(ps ...predicate.Paste) *PasteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *PasteUpdate) SetSlug(v string) *PasteUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *PasteUpdate) SetNillableSlug(v *string) *PasteUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PasteUpdate) SetTitle(v string) *PasteUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PasteUpdate) SetNillableTitle(v *string) *PasteUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *PasteUpdate) ClearTitle() *PasteUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetContent sets the "content" field.
func (_u *PasteUpdate) SetContent(v string) *PasteUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PasteUpdate) SetNillableContent(v *string) *PasteUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *PasteUpdate) SetLanguage(v string) *PasteUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *PasteUpdate) SetNillableLanguage(v *string) *PasteUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *PasteUpdate) ClearLanguage() *PasteUpdate {
	_u.mutation.ClearLanguage()
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *PasteUpdate) SetIsPublic(v bool) *PasteUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *PasteUpdate) SetNillableIsPublic(v *bool) *PasteUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *PasteUpdate) SetExpiresAt(v time.Time) *PasteUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *PasteUpdate) SetNillableExpiresAt(v *time.Time) *PasteUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *PasteUpdate) ClearExpiresAt() *PasteUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PasteUpdate) SetUpdatedAt(v time.Time) *PasteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PasteMutation object of the builder.
func (_u *PasteUpdate) Mutation() *PasteMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PasteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PasteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PasteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PasteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PasteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paste.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PasteUpdate) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := paste.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Paste.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := paste.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Paste.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := paste.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Paste.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := paste.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "Paste.language": %w`, err)}
		}
	}
	return nil
}

func (_u *PasteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paste.Table, paste.Columns, sqlgraph.NewFieldSpec(paste.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(paste.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(paste.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(paste.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(paste.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(paste.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(paste.FieldLanguage, field.TypeString)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(paste.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(paste.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(paste.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paste.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paste.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PasteUpdateOne is the builder for updating a single Paste entity.
type PasteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PasteMutation
}

// SetSlug sets the "slug" field.
func (_u *PasteUpdateOne) SetSlug(v string) *PasteUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *PasteUpdateOne) SetNillableSlug(v *string) *PasteUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PasteUpdateOne) SetTitle(v string) *PasteUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PasteUpdateOne) SetNillableTitle(v *string) *PasteUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *PasteUpdateOne) ClearTitle() *PasteUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetContent sets the "content" field.
func (_u *PasteUpdateOne) SetContent(v string) *PasteUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PasteUpdateOne) SetNillableContent(v *string) *PasteUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *PasteUpdateOne) SetLanguage(v string) *PasteUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *PasteUpdateOne) SetNillableLanguage(v *string) *PasteUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *PasteUpdateOne) ClearLanguage() *PasteUpdateOne {
	_u.mutation.ClearLanguage()
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *PasteUpdateOne) SetIsPublic(v bool) *PasteUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *PasteUpdateOne) SetNillableIsPublic(v *bool) *PasteUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *PasteUpdateOne) SetExpiresAt(v time.Time) *PasteUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *PasteUpdateOne) SetNillableExpiresAt(v *time.Time) *PasteUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *PasteUpdateOne) ClearExpiresAt() *PasteUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PasteUpdateOne) SetUpdatedAt(v time.Time) *PasteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PasteMutation object of the builder.
func (_u *PasteUpdateOne) Mutation() *PasteMutation {
	return _u.mutation
}

// Where appends a list predicates to the PasteUpdate builder.
func (_u *PasteUpdateOne) Where(ps ...predicate.Paste) *PasteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PasteUpdateOne) Select(field string, fields ...string) *PasteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Paste entity.
func (_u *PasteUpdateOne) Save(ctx context.Context) (*Paste, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PasteUpdateOne) SaveX(ctx context.Context) *Paste {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PasteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PasteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PasteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paste.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PasteUpdateOne) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := paste.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Paste.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := paste.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Paste.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := paste.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Paste.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := paste.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "Paste.language": %w`, err)}
		}
	}
	return nil
}

func (_u *PasteUpdateOne) sqlSave(ctx context.Context) (_node *Paste, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paste.Table, paste.Columns, sqlgraph.NewFieldSpec(paste.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Paste.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paste.FieldID)
		for _, f := range fields {
			if !paste.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paste.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(paste.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(paste.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(paste.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(paste.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(paste.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(paste.FieldLanguage, field.TypeString)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(paste.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(paste.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(paste.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paste.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Paste{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paste.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
