// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/piotmni/go-mini-templates/ent-atlas/ent/paste"
	"github.com/piotmni/go-mini-templates/ent-atlas/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	pasteFields := schema.Paste{}.Fields()
	_ = pasteFields
	// pasteDescSlug is the schema descriptor for slug field.
	pasteDescSlug := pasteFields[0].Descriptor()
	// paste.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	paste.SlugValidator = func() func(string) error {
		validators := pasteDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pasteDescTitle is the schema descriptor for title field.
	pasteDescTitle := pasteFields[1].Descriptor()
	// paste.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	paste.TitleValidator = pasteDescTitle.Validators[0].(func(string) error)
	// pasteDescContent is the schema descriptor for content field.
	pasteDescContent := pasteFields[2].Descriptor()
	// paste.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	paste.ContentValidator = pasteDescContent.Validators[0].(func(string) error)
	// pasteDescLanguage is the schema descriptor for language field.
	pasteDescLanguage := pasteFields[3].Descriptor()
	// paste.DefaultLanguage holds the default value on creation for the language field.
	paste.DefaultLanguage = pasteDescLanguage.Default.(string)
	// paste.LanguageValidator is a validator for the "language" field. It is called by the builders before save.
	paste.LanguageValidator = pasteDescLanguage.Validators[0].(func(string) error)
	// pasteDescIsPublic is the schema descriptor for is_public field.
	pasteDescIsPublic := pasteFields[4].Descriptor()
	// paste.DefaultIsPublic holds the default value on creation for the is_public field.
	paste.DefaultIsPublic = pasteDescIsPublic.Default.(bool)
	// pasteDescCreatedAt is the schema descriptor for created_at field.
	pasteDescCreatedAt := pasteFields[6].Descriptor()
	// paste.DefaultCreatedAt holds the default value on creation for the created_at field.
	paste.DefaultCreatedAt = pasteDescCreatedAt.Default.(func() time.Time)
	// pasteDescUpdatedAt is the schema descriptor for updated_at field.
	pasteDescUpdatedAt := pasteFields[7].Descriptor()
	// paste.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paste.DefaultUpdatedAt = pasteDescUpdatedAt.Default.(func() time.Time)
	// paste.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paste.UpdateDefaultUpdatedAt = pasteDescUpdatedAt.UpdateDefault.(func() time.Time)
}
