// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PastesColumns holds the columns for the "pastes" table.
	PastesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "slug", Type: field.TypeString, Unique: true, Size: 20},
		{Name: "title", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "language", Type: field.TypeString, Nullable: true, Size: 50, Default: "plaintext"},
		{Name: "is_public", Type: field.TypeBool, Default: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PastesTable holds the schema information for the "pastes" table.
	PastesTable = &schema.Table{
		Name:       "pastes",
		Columns:    PastesColumns,
		PrimaryKey: []*schema.Column{PastesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "paste_slug",
				Unique:  false,
				Columns: []*schema.Column{PastesColumns[1]},
			},
			{
				Name:    "paste_created_at",
				Unique:  false,
				Columns: []*schema.Column{PastesColumns[7]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PastesTable,
	}
)

func init() {
}
